### ISSUE TITLE
Sign in with username

### ISSUE THREAD

**Issue by MartinaB91** [MartinaB91/project4-my-blog#3]
## Description:
_This epic is about letting the user and admin sign in/out to the blog_

## User stories:
- [ ] #19 
- [ ] #28 

## Tasks:
- [x] https://github.com/MartinaB91/project4-my-blog/issues/31
- [x] https://github.com/MartinaB91/project4-my-blog/issues/34
- [x] https://github.com/MartinaB91/project4-my-blog/issues/35
- [x] https://github.com/MartinaB91/project4-my-blog/issues/42

## Tests
- [x] #55 
- [x] #56
