### ISSUE TITLE
Project planning and design

### ISSUE THREAD

**Issue by MartinaB91** [MartinaB91/project4-my-blog#8]
## Description:
_This epic is about planning and design of the blog project_

## Task: 
- [x] https://github.com/MartinaB91/project4-my-blog/issues/9#
- [x] https://github.com/MartinaB91/project4-my-blog/issues/10#
- [x] https://github.com/MartinaB91/project4-my-blog/issues/11#
